### PR TITLE
Fix clang cross compile command

### PR DESCRIPTION
**Pull request by infinitebash**
The command `make ARCH=arm64 CROSS_COMPILE=clang LLVM=1 -j$(nproc) Image.lzma dtbs` threw the following error on my machine (Arch Linux with clang 13.0.1): 
```
error: unknown target triple 'clang', please use -triple or -arch
```

However `make ARCH=arm64 CROSS_COMPILE=clang-arm64 LLVM=1 -j$(nproc) Image.lzma dtbs` did work.

### CODE REVIEW

**Comment by konradybcio** [comment]
isn't `clang-arm64` an Arch specific? 

ClangBuiltLinux uses

`make ARCH=arm64 LLVM=1 LLVM_IAS=1 LLVM_VERSION=15`

not sure how necessary the last paremeter is though and I can't really test rn

**Comment by alamshafil** [comment]
I get the same error on Arch Linux; however, using:
```
make ARCH=arm64 LLVM=1 LLVM_IAS=1 LLVM_VERSION=15 -j$(nproc) Image.lzma dtbs
```

Works fine for me on Arch Linux.

**Comment by DiscoStarslayer** [comment]
I was able to build on ubuntu with `make ARCH=arm64 LLVM=-14` (`-14` specifies to use version 14 of the clang toolchain). The kernel docs specify the CROSS_COMPILE property is redundant when clang is being used.

**Comment by infinitebash** [comment]
The command `make ARCH=arm64 LLVM=1 -j$(nproc) Image.lzma dtbs` worked for me as well so I've updated my repo/PR to use it (as well as pulling changes from upstream).

**Pull request merged**
